version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: etrosa:${ETROSA_VERSION:-latest}
    restart: always
    env_file:
    - .env
    environment:
      ETROSA_HOST: 0.0.0.0
      ETROSA_DB_FILE: /db_data/db.sqlite3
    volumes:
    - etrosa-db-data:/db_data/

  migrator:
    image: etrosa:${ETROSA_VERSION:-latest}
    restart: "no"
    command: alembic upgrade head
    environment:
      ETROSA_DB_FILE: /db_data/db.sqlite3
    volumes:
    - etrosa-db-data:/db_data/



volumes:
  etrosa-db-data:
    name: etrosa-db-data
