version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: etrosa:${ETROSA_VERSION:-latest}
    restart: always
    env_file:
    - .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      ETROSA_HOST: 0.0.0.0
      ETROSA_DB_HOST: etrosa-db
      ETROSA_DB_PORT: 3306
      ETROSA_DB_USER: etrosa
      ETROSA_DB_PASS: etrosa
      ETROSA_DB_BASE: etrosa

  db:
    image: bitnami/mysql:8.0.30
    hostname: etrosa-db
    restart: always
    environment:
      MYSQL_ROOT_USER: "etrosa"
      MYSQL_ROOT_PASSWORD: "etrosa"
      MYSQL_DATABASE: "etrosa"
      MYSQL_AUTHENTICATION_PLUGIN: "mysql_native_password"
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 10s
      timeout: 5s
      retries: 40
    volumes:
    - etrosa-db-data:/bitnami/mysql/data

  migrator:
    image: etrosa:${ETROSA_VERSION:-latest}
    restart: "no"
    command: aerich upgrade
    environment:
      ETROSA_DB_HOST: etrosa-db
      ETROSA_DB_PORT: 3306
      ETROSA_DB_USER: etrosa
      ETROSA_DB_PASS: etrosa
      ETROSA_DB_BASE: etrosa
    depends_on:
      db:
        condition: service_healthy



volumes:
  etrosa-db-data:
    name: etrosa-db-data
